# test files are of the form
# comment
# #-#-#
# code
# #-#-#
# output
# this allows for testing of errors etc where the error message generated by ocaml is known
# comment is mandatory and gives an overview of the purpose of the test
errors = []

Dir["test/*_test.aa"].each do |file|
  test_data = File.read(file)
  comment, code, expected_output = test_data.split('#-#-#').collect { |str| str.strip }
  if code.nil?
    abort "#{file} appears to in an incorrect format"
  end
  File.open('./test/test.aa', 'w') { |f| f.write(code) }
  r, w = IO.pipe
  pid = spawn('./language test/test.aa', out: w, err: w)
  Process.wait pid
  w.close
  result = r.read.strip
  if result == expected_output
    print "."
  else
    errors << %(expected "#{result}" to equal "#{expected_output}")
    print "F"
  end
end

File.delete './test/test.aa'

print "\n"

if errors.length > 0
  errors.map { |str| puts str }
  exit 1
end
